name: 'tagger-action'
description: 'Tag commit with a given ref'
author: 'Jiang Yucheng'
inputs:
  owner:
    required: true
    description: 'The github repo owner'
  repo:
    required: true
    description: 'the github repo name'
  token:
    required: true
    description: 'The GITHUB_TOKEN secret'
  tag:
    required: true
    description: 'Tag text'
  ref:
    required: true
    description: 'A given ref'
runs:
  using: 'node12'
  main: 'dist/index.js'
